[env:adafruit_feather_m0_express]
platform = atmelsam
board = adafruit_feather_m0_express
framework = arduino
lib_deps =
    https://github.com/iwanders/OBD9141
    https://github.com/RobTillaart/X9C10X


monitor_speed = 115200